C branch (#8)

diff --git a/condiction-workflow.yml b/condiction-workflow.yml
--- a/condiction-workflow.yml
+++ b/condiction-workflow.yml
@@ -1,66 +1,97 @@
-name: Conditional Workflow
+name: condiction scan
 
 on:
   push:
     branches:
-      - '**'
+      - "**"
+
 
 jobs:
-  check-config:
+
+  check-scan-configuration:
     runs-on: ubuntu-latest
+    env:
+      CONFIG_FILE_PATH: con.config
     outputs:
-      should_run: ${{ steps.check-branch.outputs.should_run }}
+        should_run: ${{ steps.check-branch.outputs.should_run }}
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+        - name: sparse-checkout the config file
+          uses: actions/checkout@v4
+          with:
+            sparse-checkout: |
+              ${{ env.CONFIG_FILE_PATH }}
+            sparse-checkout-cone-mode: false
 
-      - name: Read config file
-        id: read-config
-        shell: bash
-        run: |
-          # check if the config file exists
-          if [[ -f config.yml ]]; then
+        - name: Read config file for run_on_branches info
+          id: read-config
+          shell: bash
+          run: |
+            # check if the config file exists
+            if [ -f $CONFIG_FILE_PATH ]; then
+                # grab the line
+                branch_config=$(grep '^branches=' $CONFIG_FILE_PATH || echo '')
 
-            # use awk to extract the run_on_branches list
-            run_on_branches=$(awk '
-                /run_on_branches:/ {flag=1; next}       # find the run_on_branches key
-                /^[^[:space:]]/ {flag=0}                # stop when a new key is found
-                flag {
-                    gsub(/^[[:space:]]*-[[:space:]]*["'\'']?/, "")   # remove leading spaces, dashes, and potential quotes
-                    gsub(/["'\'']$/, "")                 # remove trailing quotes
-                    print
-                }
-            ' config.yml)
+                if [[ -z "$branch_config" ]]; then
+                    echo "branches=" >> $GITHUB_OUTPUT
+                    echo "no branches config found in config file"
+                else
+                    echo "$branch_config" >> $GITHUB_OUTPUT
+                    echo "$branch_config"
+                fi
+            else
+                echo "Config file not found"
+            fi
+        
+        - name: Check if branch should run
+          id: check-branch
+          shell: bash
+          run: |
+            # helper function to convert github action's pattern matching (which is fnmatch) to regex
+            # not using fnmatch because it is not available in Github Action runners
+            
+            convert_to_regex() {
+              # escape the following special characters: (){}+|
+              local regex_result=$(echo "$1" | sed "s/[(){}+|]/\\\\&/g")
 
-            # convert newlines to spaces, and remove leading and trailing spaces
-            run_on_branches=$(echo "$run_on_branches" | tr '\n' ' ' | sed 's/[[:space:]]*$//')
+              # convert the branch name to a regex pattern
+              # replace . with \.  ;;  * with [^/]*  ;;  ? with .{1}
+              # ** will become [^/]*[^/]*  ;; hence the seconde sed command
+              regex_result=$(echo "$regex_result" | sed 's/\./\\./g; s/\*/[^\/]*/g; s/\?/.{1}/g')
 
-            # set the run_on_branches output to GITHUB_OUTPUT
-            echo "run_on_branches=$run_on_branches" >> "$GITHUB_OUTPUT"
-            echo "run_on_branches=$run_on_branches"
+              # replace [^/]*[^/]*  with .*  ;; this completes ** to .*
+              regex_result=$(echo "$regex_result" | sed 's/\[\^\/\]\*\[\^\/\]\*/.*/g')
 
+              # finally, hanle the negation of a character set
+              # eg. [!abc] will become [^abc]
+              regex_result=$(echo "$regex_result" | sed 's/\[\!/\[\^/g')
 
-          else
+              # return the regex
+              echo "$regex_result"
+            }
 
-            # if the config file does not exist, do not set the run_on_branches output
-            echo "run_on_branches=" >> "$GITHUB_OUTPUT"
-            echo "Config file not found. The job will run regardless."
-          fi
+            # ----------------- main script -----------------
 
-      - name: Check if branch should run
-        id: check-branch
-        shell: bash
-        run: |
-          # get the current branch name
-          current_branch=${GITHUB_REF#refs/heads/}
-          echo "current_branch=$current_branch"
+            # get the current branch name
+            current_branch=${GITHUB_REF#refs/heads/}
+            echo "current_branch=$current_branch"
 
-          should_run=false
-          run_on_branches="${{ steps.read-config.outputs.run_on_branches }}"
+            # get the default branch name
+            default_branch=${{ github.event.repository.default_branch }}
+            echo "default_branch=$default_branch"
 
-          # fause safe default: if the config does not exist, the job should run regardless
-            if [[ -z "$run_on_branches" ]]; then
+            should_run=false
+            run_on_branches="${{ steps.read-config.outputs.branches }}"
+
+            # fause safe default: 
+            # 1. no matter what the config says, the job should run on the default branch
+            # 2. if the config does not exist, the job should run regardless
+            
+            if [[ "$current_branch" == "$default_branch" ]]; then
                 should_run=true
+                echo "current branch is the default branch, job will run"
+            elif [[ -z "$run_on_branches" ]] ; then
+                should_run=true
+                echo "no run_on_branches config found in config file, job will run on all branches"
             else
                 
                 echo "run_on_branches=$run_on_branches"
@@ -71,32 +102,50 @@ jobs:
                 # iterate over the branches
                 for branch in "${branches[@]}"; do
 
-                    # convert the branch name to a regex pattern
-                    regex=$(echo "$branch" | sed 's/\./\\./g; s/\*/.*/g; s/\?/.{1}/g')
+                    # convert the github action's branch pattern into regex
+                    regex=$(convert_to_regex "$branch")
 
                     # check if the current branch matches the pattern
-                    if [[ "$current_branch" =~ ^$regex$ ]]; then
+                    # the following if block is for Github Actions's negate pattern
+
+                    negate=false
+                    # if there is a negte character "!"
+                    if [[ $regex =~ ^! ]]; then
+                        # remove the "!" character
+                        regex=${regex:1}
+                        negate=true
+                    fi
+
+                    # if the current branch matches the pattern and negate is false, set should_run to true
+                    if [[ "$current_branch" =~ ^$regex$ ]] && [[ $negate == false ]]; then
                         should_run=true
+                        echo "current branch ($current_branch) matches the pattern: $branch, job will run"
                         break
+                    elif [[ $negate == true ]]; then
+                        # if the current branch does not match the pattern and negate is true, set should_run to true
+                        if [[ "$current_branch" =~ ^$regex$ ]]; then
+                            : # do nothing
+                            # using this empty if block because regex negation is .... not working as expected
+                        else
+                            should_run=true
+                            echo "current branch ($current_branch) matches the pattern: $branch, job will run"
+                            break
+                        fi
                     fi
                 done
             fi
-          
-          echo "should_run=$should_run" >> "$GITHUB_OUTPUT"
+            
+            echo "should_run=$should_run" >> "$GITHUB_OUTPUT"
+        
 
-  do-stuff:
-    runs-on: ubuntu-latest
-    needs: check-config
-    if: needs.check-config.outputs.should_run == 'true'
-    steps:
-      # Add your steps here
-      - name: Do stuff
-        run: echo "Doing stuff because the conditions were met."
 
-  mark-check:
+
+
+  scan:
     runs-on: ubuntu-latest
-    needs: check-config
-    if: needs.check-config.outputs.should_run == 'false'
+    needs: check-scan-configuration
+    if: needs.check-scan-configuration.outputs.should_run != 'false'
     steps:
-      - name: Mark as checked
-        run: echo "Skipped because the current branch is not in the allowed branches list."
+        - name: dummy action
+          run: |
+            echo "dummy mend scan"
