add abother false safe default
fix typos

debug mode on

debug

fix condiction brcket

more debug

putting the ! in the right place

logic?

confirmed the logic fix

remove quotes from the default_branch var

update bash comment

add explanation of why a empty if block

add false default if no entry is found in grep

add false safe default on scan job condition

diff --git a/.github/workflows/condiction-workflow.yml b/.github/workflows/condiction-workflow.yml
--- a/.github/workflows/condiction-workflow.yml
+++ b/.github/workflows/condiction-workflow.yml
@@ -29,7 +29,7 @@ jobs:
             # check if the config file exists
             if [ -f $CONFIG_FILE_PATH ]; then
                 # grab the line
-                branch_config=$(grep '^branches=' $CONFIG_FILE_PATH) 
+                branch_config=$(grep '^branches=' $CONFIG_FILE_PATH || echo '')
 
                 if [[ -z "$branch_config" ]]; then
                     echo "branches=" >> $GITHUB_OUTPUT
@@ -39,25 +39,26 @@ jobs:
                     echo "$branch_config"
                 fi
             else
-                echo "github-management-mend.config not found"
+                echo "Config file not found"
             fi
         
         - name: Check if branch should run
           id: check-branch
           shell: bash
           run: |
-            # helper function to convert github action's pattern matching to regex
+            # helper function to convert github action's pattern matching (which is fnmatch) to regex
+            # not using fnmatch because it is not available in Github Action runners
             
             convert_to_regex() {
               # escape the following special characters: (){}+|
               local regex_result=$(echo "$1" | sed "s/[(){}+|]/\\\\&/g")
 
               # convert the branch name to a regex pattern
-              # replace . with \. ;; * with [^/]* ;; ? with .{1}
+              # replace . with \.  ;;  * with [^/]*  ;;  ? with .{1}
               # ** will become [^/]*[^/]*  ;; hence the seconde sed command
               regex_result=$(echo "$regex_result" | sed 's/\./\\./g; s/\*/[^\/]*/g; s/\?/.{1}/g')
 
-              # replace [^/]*[^/]*  with .*
+              # replace [^/]*[^/]*  with .*  ;; this completes ** to .*
               regex_result=$(echo "$regex_result" | sed 's/\[\^\/\]\*\[\^\/\]\*/.*/g')
 
               # finally, hanle the negation of a character set
@@ -74,11 +75,21 @@ jobs:
             current_branch=${GITHUB_REF#refs/heads/}
             echo "current_branch=$current_branch"
 
+            # get the default branch name
+            default_branch=${{ github.event.repository.default_branch }}
+            echo "default_branch=$default_branch"
+
             should_run=false
             run_on_branches="${{ steps.read-config.outputs.branches }}"
 
-            # fause safe default: if the config does not exist, the job should run regardless
-            if [[ -z "$run_on_branches" ]]; then
+            # fause safe default: 
+            # 1. no matter what the config says, the job should run on the default branch
+            # 2. if the config does not exist, the job should run regardless
+            
+            if [[ "$current_branch" == "$default_branch" ]]; then
+                should_run=true
+                echo "current branch is the default branch, job will run"
+            elif [[ -z "$run_on_branches" ]] ; then
                 should_run=true
                 echo "no run_on_branches config found in config file, job will run on all branches"
             else
@@ -108,10 +119,16 @@ jobs:
                     # if the current branch matches the pattern and negate is false, set should_run to true
                     if [[ "$current_branch" =~ ^$regex$ ]] && [[ $negate == false ]]; then
                         should_run=true
+                        echo "current branch ($current_branch) matches the pattern: $branch, job will run"
                         break
-                    else
-                        if $negate && ! [[ $test_branch =~ ^$regex$ ]]; then
+                    elif [[ $negate == true ]]; then
+                        # if the current branch does not match the pattern and negate is true, set should_run to true
+                        if [[ "$current_branch" =~ ^$regex$ ]]; then
+                            : # do nothing
+                            # using this empty if block because regex negation is .... not working as expected
+                        else
                             should_run=true
+                            echo "current branch ($current_branch) matches the pattern: $branch, job will run"
                             break
                         fi
                     fi
@@ -127,7 +144,7 @@ jobs:
   scan:
     runs-on: ubuntu-latest
     needs: check-scan-configuration
-    if: needs.check-scan-configuration.outputs.should_run == 'true'
+    if: needs.check-scan-configuration.outputs.should_run != 'false'
     steps:
         - name: dummy action
           run: |
