add false default if no entry is found in grep
add false safe default on scan job condition

diff --git a/.github/workflows/condiction-workflow.yml b/.github/workflows/condiction-workflow.yml
--- a/.github/workflows/condiction-workflow.yml
+++ b/.github/workflows/condiction-workflow.yml
@@ -29,7 +29,7 @@ jobs:
             # check if the config file exists
             if [ -f $CONFIG_FILE_PATH ]; then
                 # grab the line
-                branch_config=$(grep '^branches=' $CONFIG_FILE_PATH) 
+                branch_config=$(grep '^branches=' $CONFIG_FILE_PATH || echo '')
 
                 if [[ -z "$branch_config" ]]; then
                     echo "branches=" >> $GITHUB_OUTPUT
@@ -39,7 +39,7 @@ jobs:
                     echo "$branch_config"
                 fi
             else
-                echo "github-management-mend.config not found"
+                echo "Config file not found"
             fi
         
         - name: Check if branch should run
@@ -144,7 +144,7 @@ jobs:
   scan:
     runs-on: ubuntu-latest
     needs: check-scan-configuration
-    if: needs.check-scan-configuration.outputs.should_run == 'true'
+    if: needs.check-scan-configuration.outputs.should_run != 'false'
     steps:
         - name: dummy action
           run: |
